## PA#2

**_Normalization Problem_**   

In [8]:
import numpy as np #Start of program

X = np.random.rand(5, 5) #Create randomized array

#Normalize array
X_mean = X.mean()
X_std = X.std()
X_normalized = (X - X_mean) / X_std

#Save normalized array
np.save('X_normalized.npy', X_normalized)

#Print
print("Original Array X:\n", X)
print("Mean of X:", X_mean)
print("Standard Deviation of X:", X_std)
print("Normalized Array X_normalized:\n", X_normalized)


Original Array X:
 [[0.89495275 0.79194062 0.46937287 0.9908733  0.57155289]
 [0.61821075 0.83270164 0.39095482 0.02299581 0.66421358]
 [0.20066791 0.14777649 0.74438209 0.52578507 0.24334674]
 [0.26934202 0.64291909 0.05317321 0.66129446 0.45950707]
 [0.24380284 0.17935431 0.47846855 0.047982   0.97413193]]
Mean of X: 0.48478811147823764
Standard Deviation of X: 0.2906815655247371
Normalized Array X_normalized:
 [[ 1.41104453  1.05666319 -0.05303135  1.74102953  0.29848739]
 [ 0.45899932  1.19688885 -0.32280442 -1.58865355  0.61725782]
 [-0.97742765 -1.15938424  0.89305277  0.14103734 -0.83060436]
 [-0.74117563  0.5440007  -1.48483754  0.60721548 -0.08697162]
 [-0.82903528 -1.0507505  -0.0217405  -1.5026963   1.68343602]]


**_Divisible by 3 Problem_**

In [8]:
import numpy as np #Start of program

#Create 10x10 array with the squares of <100 numbers
A = np.arange(1, 101)**2
A = A.reshape(10, 10)

#Check elements that can be divided by 3
div_by_3 = A[A % 3 == 0]

#Save the result
np.save('div_by_3.npy', div_by_3)

#Print
print("Array A (10x10 ndarray of squares):\n", A)
print("Elements divisible by 3:\n", div_by_3)


Array A (10x10 ndarray of squares):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
